### ISSUE TITLE
[FR] (Add Seconds to Infoscreen)

### ISSUE THREAD

**Issue by amarildolsouza** [ils15/BlueR#1]
### Feature Workflow

1. [
![seconds_001](https://user-images.githubusercontent.com/72209805/94870848-ffad2780-041e-11eb-977c-1ac969f1a182.png)
![seconds_002](https://user-images.githubusercontent.com/72209805/94870855-02a81800-041f-11eb-98ee-3cfd903cc4ab.png)

First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ils15** [comment]
Preciso verificar se cabe no display
acho que é até simples de fazer
mas algumas features requests como essas podem ser direcionadas diretas ao marlin 

o @rhapsody é o responsável por mexer na color UI

**Comment by ils15** [comment]
A maior parte das FR que voce solicitou dependem diretamente do desenvolvimento do Marlin em si, e nõa tem relação direta com a minha compilação
recomendo usar o PR do próprio Marlin para isso

https://github.com/MarlinFirmware/Marlin/pulls
