### ISSUE TITLE
[FR] (Add individual HOME for X,Y,Z)

### ISSUE THREAD

**Issue by amarildolsouza** [ils15/BlueR#3]
### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
![home for X,Y,Z](https://user-images.githubusercontent.com/72209805/94871072-8235e700-041f-11eb-832b-c8eccc00e786.png)

**Comment by ils15** [comment]
Envie a sua requisição para o @rhapsodyv, mas acredito que o layout atual é muito poluido em relação a isso

**Comment by ils15** [comment]
A maior parte das FR que voce solicitou dependem diretamente do desenvolvimento do Marlin em si, e nõa tem relação direta com a minha compilação
recomendo usar o PR do próprio Marlin para isso

https://github.com/MarlinFirmware/Marlin/pulls
