### ISSUE TITLE
[FR] (Option to turn On/Off motor invert X,Y,Z,E0,E1)

### ISSUE THREAD

**Issue by amarildolsouza** [ils15/BlueR#4]
### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ils15** [comment]
a unica forma de inverter os motores no marlin sem precisar compilar é setando valores negativos para os passos
