### ISSUE TITLE
[FR] (Option to choose between A4988 and TMC2208/TMC2209/TMC2225,etc)

### ISSUE THREAD

**Issue by amarildolsouza** [ils15/BlueR#5]
### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ils15** [comment]
Você pode fazer isso
basta compilar o Marlin e selecionar a opção correta
Também não é uma função nativa e possível na firmware
