### ISSUE TITLE
[FR] (Option to choose between normal extruder and BMG)

### ISSUE THREAD

**Issue by amarildolsouza** [ils15/BlueR#6]
### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ils15** [comment]
Foram compiladas duas firmwares de forma que isso seja contemplado
Basta baixar uma das duas versões e atualizar os passos...
Não é possível adicionar isso no display diretamente (nem na firmware que a MKS, baseada em Marlin, com a LVGL UI)
