### ISSUE TITLE
[FR] (Opção para inverter steppers, alterar passos e outras relacionadas a usar 4 TMC2225)

### ISSUE THREAD

**Issue by amarildolsouza** [ils15/BlueR#7]
### Description

Olá
       Tenho uma Bluer modelo V3 que veio com stepper driver TMC2225 no X e Y. Agora coloquei também no Z e no E.
       Porém devido a esse upgrade, tive que parar de usar seu Firmware que é o meu favorito e com melhor visualização. Gosto de saber as informações exatamente como você apresenta na tela principal.
       É possível você acrescentar as opções para inverter os Steppers assim como tem no firmware da Marlin 2.0.4 ou superior?
       Eu gosto muito do seu firmware, porém não tenho tempo no momento para estudar e chegar no seu nível de 
       conhecimento para baixar e compilar os arquivos e fazer um firmware que fique compatível com 4x TMC2225.
       Também tive que alterar os passos e velocidade do Z e E. Fiz tudo via tela do Firmware no item Machinne Setings.
       Você consegue deixar essas opções disponíveis?
       Agradeço muito sua ajuda e parabéns pelo ótimo Firmware. Gosto muito das informações apresentadas.

### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ils15** [comment]
Não é possível realizar alterações da direção dos motores de passo via LCD
mas é tranquilo compilar o firmware com as alterações requeridas
https://acelera3d.com/configurando-o-marlin-para-placas-32-bits/

Como o meu firmware já está pronto, basta baixar o source code, extrair a pasta, abrir ela via VSCODE e alterar a direção dos motores em Invert_Z e Invert_E (só inverter a lógica de true para false ou de false para true, dependendo da direção que você quiser)
